-- Supabase SQL Editor에서 실행
-- 팝업이 뜨면 현재 내부용 앱 기준으로 "Run without RLS" 선택

create table if not exists articles (
  id bigint generated by default as identity primary key,
  collected_date text not null,
  published_date text,
  source text,
  title text not null,
  url text unique,
  summary text,
  keywords text,
  category text,
  importance text default '보통',
  education_point text,
  memo text,
  is_favorite boolean default false
);

create table if not exists keywords (
  id bigint generated by default as identity primary key,
  keyword text unique not null,
  keyword_type text default '일반',
  is_active boolean default true,
  created_date text,
  last_collected_date text,
  article_count integer default 0,
  memo text
);

create table if not exists recommended_keywords (
  id bigint generated by default as identity primary key,
  keyword text unique not null,
  occurrence_count integer default 0,
  related_article_count integer default 0,
  latest_detected_date text,
  status text default 'pending',
  created_date text
);

create index if not exists idx_articles_collected_date on articles(collected_date);
create index if not exists idx_articles_importance on articles(importance);
create index if not exists idx_articles_category on articles(category);
